export const EDIT_PERSON_DETAILS = 'EDIT_PERSON_DETAILS';

export const EDIT_PERSON_NOTE = 'EDIT_PERSON_NOTE';

export const DELETE_PERSON = 'DELETE_PERSON'; 

export const ADD_TAG = 'ADD_TAG';

export const DELETE_TAG = 'DELETE_TAG';

export const ADD_ALL_TAGS = 'ADD_ALL_TAGS';

export const ADD_PERSON_DETAILS = 'ADD_PERSON_DETAILS';

export const DELETE_SELECTED_PERSONS = 'DELETE_ALL_PERSON';

export const CHANGE_COL_ORDER = 'CHANGE_COL_ORDER';

export const RESET_ALL_COLUMNS = 'RESET_ALL_COLUMNS';